language: python

os: linux

python:
  - "2.7"
  - "3.4"
  - "3.6"
  - "3.8"

before_install:
  - gem install fpm
  - gem install package_cloud
  - sudo apt-get install rpm

install: pip install --upgrade -r requirements.txt && pip install --upgrade -r requirements-dev.txt && python setup.py install

script:
  - make test
  - make lint
  - make rpm_upload
